---

- name: Update and Upgrade
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install the latest version of Kea with documentation
  ansible.builtin.dnf:
    name:
      - kea
      - kea-doc
    state: latest

- name: Template kea-dhcp4.conf to /etc/kea/kea-dhcp4.conf
  ansible.builtin.template:
    src: templates/etc/kea/kea-dhcp4.conf
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    group: kea
    mode: '0640'

...
